"""SuperCollider integration: notes, effects and SynthDefs over OSC.

The sequencer plays an **osc pattern** by sending SuperCollider note events:
one bundle per step, time-tagged on the pattern's grid, carrying the parameters
the pattern knows (freq/midinote, amp from ``v<k>``, dur from ``sus<k>``) plus
any named FX parameters configured with ``fx``.

SynthDefs reach SuperCollider the FoxDot way: the source is written to
``synthdefs/<name>.scd`` and its **path** is sent to **sclang** on the address
``/seqd``. The file ``sc/seqd.scd`` (shipped here) defines that responder and
evaluates the file, so sclang compiles it into the running server.
"""

import os
import re
import threading
import time

import osc
import scdefs

DEFAULT_SERVER_PORT = 57110     # scsynth
DEFAULT_SCLANG_PORT = 57120     # sclang (SynthDef definitions, '/seqd')
DEFAULT_SYNTH = "seq"
DEFAULT_HOST = "127.0.0.1"
FIRST_NODE = 2000               # node ids we hand out (FoxDot starts at 1000)
DEFAULT_LATENCY = 0.2           # s added to a bundle's time tag (FoxDot: 0.25)
MIN_LATENCY = 0.0
MAX_LATENCY = 2.0
DEFAULT_GROUP = 1               # scsynth's default group
NODE_WRAP = 100000              # stop growing the node id forever

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SYNTHDEF_DIR = os.path.join(BASE_DIR, "synthdefs")
HELPER_FILE = os.path.join(BASE_DIR, "sc", "seqd.scd")

# Parameters a note event may carry; the template below accepts them all, and
# scsynth ignores names a SynthDef does not declare.
NOTE_PARAMS = ("cutoff", "resonance", "drive", "delay", "reverb", "pan")


def server_target(host=None, port=None):
    """('127.0.0.1', 57110) style server target."""
    return (host or DEFAULT_HOST, int(port or DEFAULT_SERVER_PORT))


def sclang_target(host=None, port=None):
    """('127.0.0.1', 57120) style sclang target."""
    return (host or DEFAULT_HOST, int(port or DEFAULT_SCLANG_PORT))


def parse_target(text, default_port):
    """Parse 'host:port', 'host' or ':port' -> (host, port). Raises ValueError."""
    raw = (text or "").strip()
    if not raw:
        raise ValueError("empty address")
    host, _, port_text = raw.partition(":")
    host = host.strip() or DEFAULT_HOST
    try:
        port = int(port_text) if port_text.strip() else int(default_port)
    except ValueError:
        raise ValueError(f"'{port_text}' is not a port number")
    if not 1 <= port <= 65535:
        raise ValueError(f"port {port} is out of range (1..65535)")
    return host, port


def catalogue_names():
    """Names of the built-in SynthDefs (see scdefs.py)."""
    return scdefs.names()


def catalogue_description(name):
    """One-line description of a built-in SynthDef ('' when unknown)."""
    return scdefs.describe(name)


def synthdef_source(name, params=None, out_bus=0):
    """SuperCollider source of a SynthDef.

    A name from the catalogue (scdefs.py) gives that definition; anything else
    falls back to the generic template below, whose controls are exactly what an
    osc pattern sends (freq/midinote, amp, dur, pan + NOTE_PARAMS) and whose
    envelope frees the node when it finishes.
    """
    try:
        return scdefs.source(name)
    except KeyError:
        pass
    names = [p for p in (params or NOTE_PARAMS) if p != "pan"]
    controls = ("|out = %d, freq = 440, amp = 0.4, dur = 0.5, "
                "pan = 0, atk = 0.01, rel = 0.25, %s|"
                % (out_bus, ", ".join(f"{p} = {_default_for(p)}"
                                      for p in names)))
    body = f"""// '{name}' SynthDef - generated by seq.py ('synthdef {name}').
// Edit freely, then re-send with 'synthdef {name}' (or 'synthdef {name} file').
SynthDef(\\{name}, {{ {controls}
    var sig, env, tail;
    env = EnvGen.kr(
        Env([0, 1, 1, 0], [atk, (dur - atk - rel).max(0.01), rel]),
        doneAction: 2);
    sig = (Saw.ar(freq) * 0.4) + (Pulse.ar(freq, 0.5) * 0.2);
    sig = RLPF.ar(sig, cutoff.clip(30, 18000), resonance.clip(0.05, 1));
    sig = (sig * drive.clip(0.05, 8)).tanh;
    tail = DelayC.ar(sig, 1, delay.clip(0, 1)) * 0.5;
    sig = sig + tail;
    sig = FreeVerb.ar(sig, reverb.clip(0, 1), 0.8, 0.2);
    Out.ar(out, Pan2.ar(sig * env * amp, pan.clip(-1, 1)));
}}).add;
"""
    return body


def _default_for(param):
    return {"cutoff": 4000, "resonance": 0.5, "drive": 1, "delay": 0,
            "reverb": 0}.get(param, 0)


NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def safe_name(name):
    """Validate a SynthDef name (a SuperCollider symbol: letters/digits/_)."""
    text = (name or "").strip().lstrip("\\")
    if not NAME_RE.match(text):
        raise ValueError(f"'{name}' is not a valid SynthDef name "
                         f"(use letters, digits and _, e.g. seq or bass2)")
    return text


def synthdef_path(name):
    return os.path.join(SYNTHDEF_DIR, f"{name}.scd")


def list_synthdefs():
    """Sorted SynthDef source files available in synthdefs/."""
    try:
        names = os.listdir(SYNTHDEF_DIR)
    except OSError:
        return []
    return sorted(n[:-4] for n in names if n.lower().endswith(".scd"))


GENERATED_MARK = "Generated by seq.py"


def ensure_synthdef_file(name):
    """Write the built-in definition for 'name' (refreshing generated files).

    A file you wrote yourself (no "Generated by seq.py" marker) is left alone;
    a generated one is refreshed, so improvements to the catalogue reach the
    SynthDefs without losing your edits.
    """
    name = safe_name(name)
    os.makedirs(SYNTHDEF_DIR, exist_ok=True)
    path = synthdef_path(name)
    if os.path.isfile(path):
        try:
            with open(path, encoding="utf-8") as handle:
                if GENERATED_MARK not in handle.read():
                    return path
        except OSError:
            pass
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(synthdef_source(name))
    return path


# Sensible ranges per effect parameter (used to clamp expressions such as
# 'cutoff 2000+1500*lfo1'); an unknown name gets a generous range.
FX_RANGES = {
    "cutoff": (20.0, 20000.0),
    "resonance": (0.05, 1.0),
    "drive": (0.05, 8.0),
    "delay": (0.0, 1.0),
    "reverb": (0.0, 1.0),
    "pan": (-1.0, 1.0),
    "amp": (0.0, 1.0),
    "atk": (0.0, 5.0),
    "rel": (0.0, 5.0),
    "rate": (0.01, 8.0),
}
DEFAULT_FX_RANGE = (-1000.0, 10000.0)


def fx_range(name):
    """(low, high) clamping range for an effect parameter."""
    return FX_RANGES.get((name or "").lower(), DEFAULT_FX_RANGE)


def freq_of(midi_note):
    """Hz of a MIDI note number."""
    return 440.0 * (2.0 ** ((float(midi_note) - 69.0) / 12.0))


class OscEmitter:
    """Turns resolved note events into SuperCollider OSC bundles.

    A note event becomes one time-tagged bundle carrying midinote/freq, amp
    (from the pattern's ``v<k>``), dur (from ``sus<k>``) and the pattern's FX
    parameters, which may be LFO expressions evaluated at that moment.

    Bundles are scheduled *in the future* by `latency` seconds: scsynth prints
    "late <t>" whenever a scheduled message arrives after its time, so the tag
    needs enough slack for the playhead's resolution plus the UDP hop (FoxDot
    uses 0.25 s; 0.2 s is the default here, `latency <s>` changes it).
    """

    def __init__(self, engine, synth=DEFAULT_SYNTH, fx=None, lfos=None,
                 bpm=120, latency=None):
        self.engine = engine
        self.synth = synth or DEFAULT_SYNTH
        self.fx = dict(fx or {})
        self.lfos = lfos or {}
        self.bpm = bpm
        self.latency = DEFAULT_LATENCY if latency is None else float(latency)
        self.notes = 0
        # Wall clock minus the monotonic clock, sampled once per cycle so the
        # grid's times convert without reading (and mixing) both clocks per note.
        self._wall_offset = time.time() - time.monotonic()

    def note_on(self, note, velocity, hold, when, seq_index=None):
        import velocity as velocity_module     # local: keeps imports light
        now = when if when else time.monotonic()
        params = {}
        for name, expr in self.fx.items():
            low, high = fx_range(name)
            try:
                params[name] = velocity_module.evaluate_span(
                    expr, self.lfos, self.bpm, now, low, high)
            except ValueError:
                continue
        # `when` is on the player's monotonic grid: shift it into wall-clock
        # time with the offset sampled at the start of this cycle, then add the
        # scheduling latency.
        # `when` is on the player's monotonic grid: convert it with the clock
        # offset sampled at the start of this cycle (no second clock reading,
        # and no mixing of multi-millisecond clocks per note).
        unix_time = (when + self._wall_offset if when else time.time())             + self.latency
        self.engine.send_note(synth=self.synth, midinote=note,
                              freq=freq_of(note),
                              amp=max(0.0, min(1.0, velocity / 127.0)),
                              dur=hold, params=params, when=unix_time,
                              absolute=True)
        self.notes += 1

    def refresh(self, settings):
        """Pick up per-cycle settings (synth name, FX, LFOs, BPM).

        Called by the player before every pass, so editing 'synth' or 'fx' takes
        effect at the start of the next cycle, like every other pattern edit.
        """
        if not settings:
            return
        self.synth = settings.get("synth") or self.synth
        if settings.get("fx") is not None:
            self.fx = dict(settings["fx"])
        if settings.get("lfos") is not None:
            self.lfos = settings["lfos"]
        if settings.get("bpm") is not None:
            self.bpm = settings["bpm"]
        if settings.get("latency") is not None:
            self.latency = float(settings["latency"])
        self._wall_offset = time.time() - time.monotonic()

    def note_off(self, note):
        """Nothing to do: the SynthDef's envelope frees the node itself."""

    def control(self, controller, value, when, seq_index=None):
        """OSC patterns send notes, not control changes."""

    def close(self):
        pass


def combined_synthdef_file(extra_sources=()):
    """Source text of every .scd in synthdefs/ (plus extra sources).

    Written to synthdefs/_all.scd by send_all_synthdefs(), so one /seqd message
    installs the whole folder at once.
    """
    chunks = []
    for name in sorted(list_synthdefs()):
        if name == "_all":
            continue
        try:
            with open(synthdef_path(name), encoding="utf-8") as handle:
                chunks.append(handle.read())
        except OSError:
            continue
    chunks.extend(extra_sources)
    stamp = ("// _all.scd - every SynthDef in synthdefs/, installed in one go "
             "by\n// 'synthdef all' (edit the individual files and re-send).\n")
    return stamp + "\n".join(chunks)


class SoundEngine:
    """OSC output for one SuperCollider (server, sclang) pair.

    One engine is shared by every osc pattern pointing at the same server, so
    the UDP socket and the node numbering stay coherent.
    """

    def __init__(self, server=None, sclang=None, latency=DEFAULT_LATENCY):
        self.server = tuple(server or server_target())
        self.sclang = tuple(sclang or sclang_target())
        self.latency = float(latency)
        self.client = osc.Client(*self.server)
        self._node = FIRST_NODE
        self._lock = threading.Lock()
        self.recording = False
        self.log = []               # last packets, as text (for 'dump')
        self.log_limit = 24
        self.sent_notes = 0
        self.last_error = None

    # -- helpers ----------------------------------------------------------
    @property
    def target_text(self):
        return f"{self.server[0]}:{self.server[1]}"

    @property
    def sclang_text(self):
        return f"{self.sclang[0]}:{self.sclang[1]}"

    def next_node(self):
        with self._lock:
            node = self._node
            self._node += 1
            if self._node > FIRST_NODE + NODE_WRAP:
                self._node = FIRST_NODE
            return node

    def _send(self, elements, when=None):
        """Send a bundle (or record it when dumping) and log it."""
        packet = osc.encode_bundle(elements, when)
        if self.recording:
            self.log.append(osc.describe(packet))
            del self.log[:-self.log_limit]
        try:
            self.client.send_bytes(packet)
            return True
        except OSError as e:        # unreachable host/port: keep playing
            self.last_error = str(e)
            return False

    # -- notes ------------------------------------------------------------
    def send_note(self, synth=DEFAULT_SYNTH, freq=None, midinote=None,
                  amp=0.5, dur=0.5, params=None, when=None, group=DEFAULT_GROUP,
                  absolute=False):
        """Send one note event as a time-tagged bundle. Returns the node id.

        `when` is seconds from now, or an absolute Unix time when absolute=True
        (an absolute time already carries the latency).
        """
        node = self.next_node()
        args = [synth, node, 1, int(group)]
        if midinote is not None:
            args += ["midinote", float(midinote)]
        if freq is not None:
            args += ["freq", float(freq)]
        args += ["amp", float(amp), "dur", max(0.01, float(dur))]
        for key, value in (params or {}).items():
            args += [str(key), float(value)]
        tag = when if absolute else self._time_tag(when)
        self._send([("/s_new", args)], tag)
        self.sent_notes += 1
        return node

    def _time_tag(self, when):
        """Unix time for a bundle: 'when' is seconds from now (None = now)."""
        if when is None:
            return None
        return time.time() + float(when) + self.latency

    def set_params(self, node, params):
        """Update running-node controls (/n_set), e.g. a persistent FX node."""
        if not params:
            return False
        args = [int(node)]
        for key, value in params.items():
            args += [str(key), float(value)]
        return self._send([("/n_set", args)], None)

    def free_all(self):
        """Stop every sound: free the default and root groups, clear the queue."""
        ok = self._send([("/g_freeAll", [DEFAULT_GROUP]),
                         ("/g_freeAll", [0]),
                         ("/clearSched", [])], None)
        return ok

    # -- SynthDefs --------------------------------------------------------
    def send_synthdef(self, name, source=None):
        """Give sclang a SynthDef file to compile.

        Writes the built-in template when no source is given (keeping an edited
        file untouched) and sends its path to /seqd. Returns (path, error).
        """
        try:
            if source is None:
                path = ensure_synthdef_file(name)
            else:
                os.makedirs(SYNTHDEF_DIR, exist_ok=True)
                path = synthdef_path(name)
                with open(path, "w", encoding="utf-8") as handle:
                    handle.write(source)
        except OSError as e:
            return None, f"cannot write {synthdef_path(name)}: {e}"
        client = osc.Client(*self.sclang)
        try:
            packet = osc.encode_message("/seqd", [path])
            if self.recording:
                self.log.append(osc.describe(packet))
                del self.log[:-self.log_limit]
            client.send_bytes(packet)
        except OSError as e:
            return path, f"cannot reach sclang at {self.sclang_text}: {e}"
        finally:
            client.close()
        return path, None

    def send_all_synthdefs(self, names=None):
        """Write every catalogue SynthDef and send them as ONE file.

        Files already in synthdefs/ are kept untouched (so your edits survive),
        missing ones are generated, then all of them are concatenated into
        synthdefs/_all.scd and that single path is sent to sclang /seqd, so one
        OSC message installs the whole set.

        Returns (path, count, error).
        """
        wanted = list(names or catalogue_names())
        written = []
        for name in wanted:
            try:
                written.append(ensure_synthdef_file(name))
            except OSError as e:
                return None, 0, f"cannot write {synthdef_path(name)}: {e}"
        combined = combined_synthdef_file()
        path, err = self.send_synthdef("_all", source=combined)
        return path, len(wanted), err

    # -- diagnostics ------------------------------------------------------
    def status(self, timeout=1.0):
        """Ask the server for /status; returns a dict or None when silent."""
        listener = osc.Listener()
        try:
            listener.start()
            listener.sock.sendto(osc.encode_message("/status"), self.server)
            reply = listener.receive("/status.reply", timeout)
        finally:
            listener.close()
        if not reply:
            return None
        args = reply[2]
        keys = ("unused", "ugens", "synths", "groups", "synthdefs",
                "avg_cpu", "peak_cpu", "sample_rate", "actual_sample_rate")
        return dict(zip(keys, args))

    def close(self):
        self.client.close()


_engines = {}
_engines_lock = threading.Lock()


def engine_for(server=None, sclang=None):
    """Shared SoundEngine for a (server, sclang) pair."""
    key = (tuple(server or server_target()), tuple(sclang or sclang_target()))
    with _engines_lock:
        engine = _engines.get(key)
        if engine is None:
            engine = SoundEngine(key[0], key[1])
            _engines[key] = engine
        return engine


def close_all():
    with _engines_lock:
        for engine in _engines.values():
            engine.close()
        _engines.clear()
